### ISSUE TITLE
Building vapor [Failed]

### ISSUE THREAD

**Issue by nhatlee** [vapor-cloud/toolbox#31]
Hi, When try `vapor cloud deploy` I got the below error. Please help me for work around or I just waiting for support `Swift4.0`?
```
Building vapor [Failed]
swift-build: error: Package requires minimum Swift tools version 4.0.0. Current Swift tools version is 3.1.0

Error: deploy failed.
```

**Comment by tanner0101** [comment]
@nhatlee you can set a `swift_version` in your `cloud.yml` file. https://docs.vapor.cloud/configuration/vapor/basic/#swift-version
